FROM resin/%%RESIN_MACHINE_NAME%%-debian:latest

ENV INITSYSTEM on

RUN apt-get update && apt-get install -y cron lockfile && \
apt-get clean && rm -rf /var/lib/apt/lists/*

COPY jobs.txt ./

RUN crontab jobs.txt

WORKDIR /usr/src/app

COPY /app ./

CMD [ "bash", "app.sh" ]
